version: '3'

services:
  developer-portal-backend:
    build: .
    image: developer-portal
    ports:
      - "5000:5000"
    environment:
      AWS_ACCESS_KEY_ID: dummy
      AWS_SECRET_ACCESS_KEY: dummy
      AWS_REGION: us-east-1
      DYNAMODB_ENDPOINT: http://dynamodb-local:8000
    depends_on: 
      - dynamodb-local
  dynamodb-local:
    build: ./dynamodb_local_latest
    image: dynamodb_local
    ports: 
      - "8000:8000"